sudo: required
language: bash
services:
- docker
env:
- DOCKER_IMAGE_NAME=webitel/freeswitch
before_install:
- if [ ! -z "$TRAVIS_TAG" ]; then sed -i 's/ENV VERSION/ENV VERSION '${TRAVIS_TAG}'-sha1:'${TRAVIS_COMMIT:0:7}'/g'
  Dockerfile; else sed -i 's/ENV VERSION/ENV VERSION master sha1:'${TRAVIS_COMMIT:0:7}'/g'
  Dockerfile; fi
- if [ ! -z "$TRAVIS_TAG" ]; then sed -i 's/ENV WEBITEL_MAJOR/ENV WEBITEL_MAJOR '${TRAVIS_TAG}'/g'
  Dockerfile; else sed -i 's/ENV WEBITEL_MAJOR/ENV WEBITEL_MAJOR '${TRAVIS_COMMIT:0:7}'/g'
  Dockerfile; fi
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
install:
- docker build --no-cache -t $DOCKER_IMAGE_NAME .
script:
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi && docker push $DOCKER_IMAGE_NAME
